version: '3.9'

services:
  # apache-init:
  #   image: apache
  #   command: >
  #     bash -c "
  #       mkdir -p /mnt/conf /mnt/htdocs &&
  #       cp -r /usr/local/apache2/conf/* /mnt/conf 2>/dev/null || true &&
  #       cp -r /usr/local/apache2/htdocs/* /mnt/htdocs 2>/dev/null || true"
  #   volumes:
  #     - ./data/conf:/mnt/conf
  #     - ./data/htdocs:/mnt/htdocs
  #   entrypoint: ""

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    # depends_on:
    #   - apache-init
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./data/conf:/usr/local/apache2/conf
      - ./data/htdocs:/usr/local/apache2/htdocs
    restart: unless-stopped
