# PHP-FPM configuration
<FilesMatch \.php$>
    SetHandler "proxy:fcgi://php:9000"
</FilesMatch>

<IfModule dir_module>
    DirectoryIndex index.php index.html
</IfModule>

# Set up PHP file types
AddType application/x-httpd-php .php
AddType application/x-httpd-php-source .phps

# PHP settings via Apache environment
<IfModule env_module>
    # Maximum upload file size
    SetEnv PHP_VALUE "upload_max_filesize=50M \n post_max_size=50M"
</IfModule>