# SVN configuration
<Location /svn>
    DAV svn
    SVNParentPath /usr/local/apache2/svn
    SVNListParentPath On
    
    # Authentication settings
    AuthType Basic
    AuthName "Subversion Repository"
    AuthUserFile /usr/local/apache2/user.passwd
    Require valid-user
</Location>